# Generated by Django 5.1.1 on 2024-09-08 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_variation_category_remove_product_variations_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productitem',
            options={'verbose_name_plural': 'Product Items'},
        ),
        migrations.AlterModelOptions(
            name='productvariation',
            options={'verbose_name_plural': 'Product Variations'},
        ),
        migrations.AddField(
            model_name='productvariation',
            name='variation_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
