# Generated by Django 5.1.1 on 2024-09-08 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_productitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
