# Generated by Django 5.1.1 on 2024-09-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_remove_cart_session_key_alter_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.AddField(
            model_name='cart',
            name='session_key',
            field=models.CharField(default='specialkey', max_length=40, unique=True),
        ),
    ]
